name: Update README

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    branches:
      - '*'
  watch:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}